on:
  workflow_run:
    workflows: [test-linux]
    types: [completed]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          mkdir -p build
          (cd build && cmake .. -DCMAKE_BUILD_TYPE=Release)
          cmake --build build
      - run: ls -a
