on:
  push:
    branches: [main]

jobs:
  test:
    name: Test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-10.15, ubuntu-18.04, ubuntu-20.04]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install dependencies
        if: runner.os == 'Linux'
        run: apt install -y valgrind
      - name: Build
        run: |
          mkdir -p build &&
            cd build &&
            cmake .. -DCMAKE_BUILD_TYPE=Debug -DBUILD_TESTS=ON &&
            cmake --build .
      - name: Test Linux
        if: runner.os == 'Linux'
        run: |
          cd build
          if ! ctest -T memcheck --output-on-failure; then
            find Testing/Temporary -name "MemoryChecker.*.log" -exec cat {} +
            exit 1
          fi
      - name: Test MacOS
        if: runner.os == 'macOS'
        run: cd build && ctest --output-on-failure
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs:
      - test
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        run: |
          mkdir -p build &&
            cd build &&
            cmake .. -DCMAKE_BUILD_TYPE=Release &&
            cmake --build build
      - name: Deploy
        run: echo Deploy
